### ISSUE TITLE
myzenwallet Error. Error: Request failed with status code 400

### ISSUE THREAD

**Issue by pedrosimao** [ZencashOfficial/myzenwallet#3]
When I try to send ZenCash from my wallet I am getting this error.
Is it a problem with the Insight API?
I have tried it on the online version of MyZenWallet too, and with two different browsers. So the problem is not on my side.

**Comment by kendricktan** [comment]
Try with fees of 0.000001

**Comment by pedrosimao** [comment]
It worked!!! Thanks a lot for the help!

**Comment by gilardh** [comment]
This request may close or must a correction be made?
